apiVersion: v2
name: openshift-logging
description: Deploy and configure OpenShift Logging including Elasticsearch and Kibana
version: 1.0.6
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/openshift-ogging
icon: https://raw.githubusercontent.com/tjungbauer/helm-charts/gh-pages/images/logging.svg
dependencies:
  - name: helper-operator
    version: "1.0.14"
    repository: https://charts.stderr.at/
  - name: helper-status-checker
    version: ~1.0.10
    repository: https://charts.stderr.at/
    condition: helper-status-checker.enabled
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
sources:
  - https://github.com/tjungbauer/helm-charts
