apiVersion: v2
name: helper-loki-bucket-secret
description: A helper Chart which creates a job to build the Secret in the format LokiStack requires.
version: 1.0.5
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/helper-loki-bucket-secret
icon: https://github.com/tjungbauer/helm-charts/raw/gh-pages/images/helping.png
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
    url: https://blog.stderr.at/
sources:
  - https://github.com/tjungbauer/helm-charts
  - https://charts.stderr.at/
  - https://github.com/tjungbauer/openshift-clusterconfig-gitops
keywords:
  - helper
  - subchart
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: B677CB52F8358FA091044E375D24D6846DBA8F8A
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/B677CB52F8358FA091044E375D24D6846DBA8F8A
  artifacthub.io/changes: |
    - kind: added
      description: Initial release
    - kind: fixed
      description: removed hardcodedstring logging
