---
override-rhacs-operator-version: &rhacsversion latest
operatornamespace: &operatornamespace rhacs-operator

# Install Operator RHACS
# Deploys Operator --> Subscription and Operatorgroup
# Syncwave: 0
helper-operator:
  operators:
    rhacs-operator:
      enabled: true
      syncwave: '0'
      namespace:
        name: *operatornamespace
        create: true
      subscription:
        channel: *rhacsversion
        approval: Automatic
        operatorName: rhacs-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: true
        # rhacs does not support to monitor own namespace,
        # therefor the spec in the OperatorGroup must be empty
        notownnamespace: true

rhacs:

  job_vars:
    max_attempts: 20  # How otften shall the status of the operator be checked (Default 20)
    wait_time: 20  # If the Deployments are not ready yet, how long shall I wait in addition (Default 20)
    crd_check_time: 5  # Time to sleep before I verify that the CRDs have been created

  namespace:
    name: stackrox
    syncwave: '0'
    descr: 'Red Hat Advanced Cluster Security'

  central:
    syncwave: '3'
    pvc: stackrox-db
    egress:
      connectivityPolicy: Online
    scannerautoscaling: Disabled

  job_init_bundle:
    syncwave: '3'

  consolelink:
    syncwave: '3'
    location: ApplicationMenu
    text: Advanced Cluster Security
    section: Observability

  secured_cluster:
    syncwave: '4'

serviceAccount:
  create: true
  name: "create-cluster-init"

helper-status-checker:
  enabled: true

  # space separate list of deployments which shall be checked for status
  deployments: "rhacs-operator-controller-manager"

  wait_time: 60  # wait time in seconds for the check-job to verify when the deployments should be ready

  namespace:
    name: rhacs-operator

  serviceAccount:
    create: true
    name: "status-checker"