---
override-rhacs-operator-version: &rhacsversion stable
operatornamespace: &operatornamespace rhacs-operator
clustername: &clustername local-cluster

# Install Operator RHACS
# Deploys Operator --> Subscription and Operatorgroup
# Syncwave: 0
helper-operator:
  operators:
    rhacs-operator:
      enabled: true
      syncwave: '0'
      namespace:
        name: *operatornamespace
        create: true
      subscription:
        channel: *rhacsversion
        approval: Automatic
        operatorName: rhacs-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: true
        # rhacs does not support to monitor own namespace,
        # therefor the spec in the OperatorGroup must be empty
        notownnamespace: true

rhacs:

  job_vars:
    max_attempts: 20  # How otften shall the status of the operator be checked (Default 20)
    wait_time: 20  # If the Deployments are not ready yet, how long shall I wait in addition (Default 20)
    crd_check_time: 5  # Time to sleep before I verify that the CRDs have been created

  namespace:
    name: stackrox
    syncwave: '0'
    descr: 'Red Hat Advanced Cluster Security'

  central:
    enabled: true
    syncwave: '3'
    pvc: stackrox-db
    egress:
      connectivityPolicy: Online
    # only route is currently possible
    scannerautoscaling:
      status: "Disabled"
      max: 1
      min: 1
      replicas: 1
    # resources for Central DB ... limit it to have more resourcen on demo systems (not for production)
    db:
      resources:
        requests:
          cpu: '1'
          memory: '1'
    # tolerations for central DB
#      tolerations:
#      - effect: NoSchedule
#        key: infra
#        operator: Equal
#        value: reserved
#    tolerations:
#    - effect: NoSchedule
#      key: infra
#      operator: Equal
#      value: reserved

    # tolerations for scanner and scanner DB
  scanner: {}
#    tolerations:
#    - effect: NoSchedule
#      key: infra
#      operator: Equal
#      value: reserved
  db: {}
#    tolerations:
#    - effect: NoSchedule
#      key: infra
#      operator: Equal
#      value: reserved

  job_init_bundle:
    enabled: true
    syncwave: '3'

  consolelink:
    enabled: true
    syncwave: '3'
    location: ApplicationMenu
    text: Advanced Cluster Security
    section: Observability

  secured_cluster:
    enabled: true
    syncwave: '4'
    clustername: *clustername

    # in case tolerations are required
    sensor: {}
    #  tolerations:
    #  - effect: NoSchedule
    #    key: infra
    #    operator: Equal
    #    value: reserved
    admissioncontrol: {}
    #  tolerations:
    #  - effect: NoSchedule
    #    key: infra
    #    operator: Equal
    #    value: reserved

  basic_acs_settings:
    auth_provider: 'OpenShift'
    auth_provider_type: 'openshift'
    min_access_role: 'None'
    syncwave: 5

serviceAccount:
  create: true
  name: "create-cluster-init"

helper-status-checker:
  enabled: true

  # use the value of the currentCSV (packagemanifest) but WITHOUT the version !!
  operatorName: rhacs-operator

  # where operator is installed
  namespace:
    name: rhacs-operator

  serviceAccount:
    create: true
    name: "status-checker"
