apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: consolebanner
spec:
  backgroundColor: "#CCCCCC"
  color: "#000000"
  link:
    href: 'https://console.redhat.com/openshift/details/{{fromClusterClaim "id.openshift.io" }}'
    text: RedHat Console
  location: BannerTop
  text: 'Name: {{ fromClusterClaim "name" }}, Version: {{ fromClusterClaim "version.openshift.io"}}'
