{{- range .Values.policies }}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: {{ .policyname }}-placement
  namespace: {{ .namespace }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
spec:
  {{- if .placement.clusterSets }}
  clusterSets:
    {{- range .placement.clusterSets }}
    - {{ . }}
    {{- end }}
  {{- end }}
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        {{- range .placement.lableSelectors }}
        - key: {{ .key }}
          operator: {{ .operator }}
          values:
          {{- range .values }}
          - {{ . }}
          {{- end }}
        {{- end }}
{{- end }}