---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: {{ .Values.policyGenerator.policyDefaults.policyname }}-placementbinding
  namespace: {{ .Values.policyGenerator.policyDefaults.namespace }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: {{ .Values.policyGenerator.policyDefaults.policyname }}-placement
subjects:
{{- if .Values.policySet }}
  {{- if eq ( .Values.policySet.enabled | toString ) "true"  }}
    {{- range .Values.policySet.sets }}
- apiGroup: policy.open-cluster-management.io
  kind: PolicySet
  name: {{ .name }}
    {{- end }}
  {{- else }}
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: {{ .Values.policyGenerator.policyDefaults.policyname }}
  {{- end }}
{{- else }}
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: {{ .Values.policyGenerator.policyDefaults.policyname }}
{{- end }}
