{{- range .Values.policies }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: {{ .policyname }}-placementbinding
  namespace: {{ .namespace }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: {{ .policyname }}-placement
subjects:
{{- if $.Values.policySet }}
  {{- if eq ( $.Values.policySet.enabled | toString ) "true"  }}
    {{- range $.Values.policySet.sets }}
- apiGroup: policy.open-cluster-management.io
  kind: PolicySet
  name: {{ .name }}
    {{- end }}
  {{- else }}
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: {{ .policyname }}
  {{- end }}
{{- else }}
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: {{ .policyname }}
{{- end }}
{{- end }}
