{{- range .Values.policies }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    {{- if $.Values.policyDefaults }}
      {{- if $.Values.policyDefaults.categories }}
    policy.open-cluster-management.io/categories: {{ join ", " $.Values.policyDefaults.categories }}
      {{- end }}
    {{- else if .categories }}
    policy.open-cluster-management.io/categories: {{ join ", " .categories }}
    {{- end }}
    {{- if $.Values.policyDefaults }}
      {{- if $.Values.policyDefaults.controls }}
    policy.open-cluster-management.io/controls: {{ join ", " $.Values.policyDefaults.controls }}
      {{- end }}
    {{- else if .controls }}
    policy.open-cluster-management.io/controls: {{ join ", " .controls }}
    {{- end }}
    {{- if $.Values.policyDefaults }}
      {{- if $.Values.policyDefaults.standards }}
    policy.open-cluster-management.io/standards: {{ join ", " $.Values.policyDefaults.standards }}
      {{- end }}
    {{- else if .standards }}
    policy.open-cluster-management.io/standards: {{ join ", " .standards }}
    {{- end }}
    {{- if $.Values.policyDefaults }}
      {{- if $.Values.policyDefaults.description }}
    policy.open-cluster-management.io/description: {{ join ", " $.Values.policyDefaults.description }}
      {{- end }}
    {{- else if .description }}
    policy.open-cluster-management.io/description: {{ .description }}
    {{- end }}
  name: {{ .policyname }}
  namespace: {{ .namespace }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
spec:
  disabled: {{ .disabled | default "true" }}
  {{- if .dependencies }}
  dependencies:
  {{- range .dependencies }}
    - name: {{ .name | quote }}
      namespace: {{ .namespace | quote }}
      compliance: {{ .compliance | default "Compliant" | quote }} 
      kind: {{ .kind | default "Policy" | quote }} 
      apiVersion: {{ .apiVersion | default "policy.open-cluster-management.io/v1" | quote }} 
  {{- end }}
  {{- end }}
  policy-templates:
    {{- range $key, $value := .policy_templates }}
    {{- $files := printf "%s/**.yaml" .path }}
    {{- range $path, $_ :=  $.Files.Glob  $files }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          {{- if $.Values.policyDefaults }}
            {{- if eq ($.Values.policyDefaults.randomizer | toString) "true" }}
          name: {{ $value.name }}-{{ randAlphaNum 4 | lower }}
            {{- else if eq ($value.randomizer | toString) "true" }}
          name: {{ $value.name }}-{{ randAlphaNum 4 | lower }}
            {{- else if eq ($value.name_use_template_filename | toString) "true" }}
          name: {{ $path | splitList "/" | last | splitList "." | first }}
            {{- else }}
          name: {{ $value.name }}
            {{- end }}
            
          {{- else if eq ($value.randomizer | toString) "true" }}
          name: {{ $value.name }}-{{ randAlphaNum 4 | lower }}
          {{- else if eq ($value.name_use_template_filename | toString) "true" }}
          name: {{ $path | splitList "/" | last | splitList "." | first }}
          {{- else }}
          name: {{ $value.name }}
          {{- end }}
        spec:
          object-templates:
            - objectDefinition:  
                {{- $.Files.Get $path | toYaml | trimAll "|-" | indent 14 }}
              complianceType: {{ $value.complianceType | default "musthave" }} 
          pruneObjectBehavior: {{ $value.pruneObjectBehavior | default "None" }}
          remediationAction: {{ $value.remediationAction | default "inform" }}
          severity: {{ $value.severity | default "low" }}
          {{- /*  */}}
          {{- if $value.namespaceSelector }}
          namespaceSelector:
            {{- if $value.namespaceSelector.include }}
            include:
            {{- range $value.namespaceSelector.include }}
              - {{ . | quote}}
            {{- end }}
            {{- end }}
            {{- if $value.namespaceSelector.exclude }}
            exclude:
            {{- range $value.namespaceSelector.exclude }}
              - {{ . | quote }}
            {{- end }}
            {{- end }}
            {{- if $value.namespaceSelector.matchExpressions }}
            matchExpressions:
            {{- range $value.namespaceSelector.matchExpressions }}
            - key: {{ .key }}
              operator: {{ .operator }}
              values:
              {{- range .values }}
              - {{ . }}
              {{- end }}
            {{- end }}
            {{- end }}
            {{- if $value.namespaceSelector.matchLabels }}
            matchLabels:
            {{- range $key, $value := $value.namespaceSelector.matchLabels }}
              {{ $key }}: {{ $value }}
            {{- end }}
            {{- end }}


      {{- end }}
      {{- if $value.evaluationInterval }}
      {{- if or ($value.evaluationInterval.compliant) ($value.evaluationInterval.noncompliant) }}
      evaluationInterval:
        {{- if $value.evaluationInterval.compliant }}
        compliant: {{ $value.evaluationInterval.compliant }}
        {{- end }}
        {{- if $value.evaluationInterval.noncompliant }}
        noncompliant: {{ $value.evaluationInterval.noncompliant }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if $value.extraDependencies }}
      extraDependencies:
        {{- range $value.extraDependencies }}
        - name: {{ $value.name | quote }}
          namespace: {{ $value.namespace | quote }}
          compliance: {{ $value.compliance | default "Compliant" | quote }} 
          kind: {{ $value.kind | default "Policy" | quote }} 
          apiVersion: {{ $value.apiVersion | default "policy.open-cluster-management.io/v1" | quote }} 
        {{- end }}
      {{- end }}

      {{- end }}
    {{- end }}
    {{- if .ignorePending }}
    ignorePending: {{ .ignorePending }}
    {{- end }}
  {{- if $.Values.policyDefaults }}
    {{- if $.Values.policyDefaults.globalRemediationAction }}
  remediationAction: {{ $.Values.policyDefaults.globalRemediationAction }}
    {{- else if .remediationAction }}
  remediationAction: {{ .remediationAction }}
    {{- end }}
  {{- else if .remediationAction }}
  remediationAction: {{ .remediationAction }}
  {{- end }}
  
{{- end }}
