{{- range .Values.banp }}
{{ if eq ( .enabled | toString) "true" }}
---
apiVersion: policy.networking.k8s.io/v1alpha1
kind: BaselineAdminNetworkPolicy
metadata:
  name: default
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncwave | default 10 | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  subject:
    {{- if .subject.matchNamespaces }}
    namespaces:
      {{- if .subject.matchNamespaces.matchExpressions }}
      matchExpressions:
        {{- range .subject.matchNamespaces.matchExpressions }}
        {{- include "tpl.matchExpressions" . | indent 4 }}
        {{- end }}
      {{- end }}
      {{- if .subject.matchNamespaces.matchLabels }}
      {{- include "tpl.matchLabels" .subject.matchNamespaces.matchLabels | indent 4 }}
      {{- end }}
    {{- end }}

    {{- if .subject.matchPods }}
    
    {{- range .subject.matchPods }}
    
  {{- include "helper.podsConfig" .pods }}
    {{- end }}
    {{- end }}

  {{- if and (not .subject.matchNamespaces) (not .subject.matchPods) }}
    namespaces: {}
  {{- end }}

  {{- /* EGRESS RULES */}}
  {{- if .egress }}
  egress:
    {{- range .egress }}
    {{- if eq ( .enabled | toString) "true" }}
    - name: {{ .name | quote }} 
      action: {{ .action | default "Deny" | quote }}
      to:
      {{- /* RENDER RULES */}}
      {{- range .peers }}
        {{- include "helper.rule" . }}
      {{- end }}

      {{- /* PORT RESTRICTION */}}
      {{- if .ports }}
      ports:
        {{- range .ports }}
          {{- include "helper.ports" . | indent 4 }}
        {{- end }}
      {{- end }}

    {{- end }}
    {{- end }}
  {{- end }}
  {{- /* END EGRESS RULES */}}
  {{- /* INGRESS RULES */}}
  {{- if .ingress }}
  ingress:
  {{- range .ingress }}
  {{- if eq ( .enabled | toString) "true" }}
    - name: {{ .name | quote }} 
      action: {{ .action | default "Deny" | quote }}
      from:
      {{- /* RENDER RULES */}}
      {{- if .peers }}
      {{- range .peers }}
        {{- include "helper.rule" . }}
      {{- end }}
      {{- else  }}
        - namespaces: {}
      {{- end }}

      {{- /* PORT RESTRICTION */}}
      {{- if .ports }}
      ports:
        {{- range .ports }}
          {{- include "helper.ports" . | indent 4 }}
        {{- end }}
      {{- end }}

    {{- end }}
    {{- end }}
  {{- end }}
  {{- /* END INGRESS RULES */}}

{{- end }}
{{- end }}
