{{ if eq ( .Values.quay.enabled | toString) "true" }}
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: quay-registry
  namespace: {{ .Values.quay.namespace.name }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.quay.syncwave | default "3" | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    {{- include "common.labels" $ | nindent 4 }}
spec:
  configBundleSecret: {{ .Values.quay.config_bundle }}
  components:
  {{- with .Values.quay.components }}
    - kind: clair
      managed: {{ .clair.managed | default "true" }}
      {{- if .clair.overrides }}
      overrides:
        {{- if .clair.overrides.replicas }}
        replicas: {{ .clair.overrides.replicas }}
        {{- end }}
      {{- end }}
    - kind: postgres
      managed: {{ .postgres.managed | default "true" }}
      {{- if .postgres.overrides }}
      overrides:
        {{- if .postgres.overrides.replicas }}
        replicas: {{ .postgres.overrides.replicas }}
        {{- end }}
      {{- end }}
    - kind: objectstorage
      managed: {{ .objectstore.managed | default "true" }}
    - kind: redis
      managed: {{ .redis.managed | default "true" }}
    - kind: horizontalpodautoscaler
      managed: {{ .hpa.managed | default "true" }}
    - kind: route
      managed: {{ .route.managed | default "true" }}
    - kind: mirror
      managed: {{ .mirror.managed | default "true" }}
      {{- if .mirror.overrides }}
      overrides:
        {{- if .mirror.overrides.replicas }}
        replicas: {{ .mirror.overrides.replicas }}
        {{- end }}
      {{- end }}
    - kind: monitoring
      managed: {{ .monitoring.managed | default "true" }}
    - kind: tls
      managed: {{ .tls.managed | default "true" }}
    - kind: quay
      managed: {{ .quay.managed | default "true" }}
      {{- if .quay.overrides }}
      overrides:
        {{- if .quay.overrides.replicas }}
        replicas: {{ .quay.overrides.replicas }}
        {{- end }}
      {{- end }}
    - kind: clairpostgres
      managed: {{ .clairpostgres.managed | default "true" }}
  {{- end }}
{{- end }}