{{- if .Values.quay }}
{{- if eq ( .Values.quay.enabled | toString) "true" }}
{{- with .Values.quay }}
{{ if eq ( .job_inject_route_cert.enabled | toString) "true" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: {{ .job_inject_route_cert.syncwave | default "5" | quote }}
  name: {{ .job_inject_route_cert.serviceAccount | default "quay-ca-injector" }}-role
  namespace: {{ $.Values.quay.namespace.name | quote }}
rules:
- verbs:
  - get
  - list
  - patch
  apiGroups:
  - ''
  resources:
  - secrets
  - configmaps
{{- end }}
{{- end }}
{{- end }}
{{- end }}
