{{- if .Values.quay }}
{{- if eq ( .Values.quay.enabled | toString) "true" }}
{{- with .Values.quay }}
{{ if eq ( .job_inject_route_cert.enabled | toString) "true" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .job_inject_route_cert.serviceAccount | default "quay-ca-injector" }}
  namespace: {{ $.Values.quay.namespace.name | quote }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: {{ .job_inject_route_cert.syncwave | default "5" | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
