apiVersion: v2
name: openshift-gitops
description: Installs and patches the Red Hat Openshift Gitops Operator
version: 1.0.8
icon: https://cncf-branding.netlify.app/img/projects/argo/stacked/color/argo-stacked-color.png
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/openshift-gitops
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
sources:
  - https://github.com/tjungbauer/helm-charts
