{{- range $key, $value := .Values.operators }}
{{ if eq ($value.enabled | toString) "true" }}
{{- if $value.operatorgroup.create }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ $key | replace "_" "-" | default "demo-operator-group" | quote }}
  namespace: {{ $value.namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: {{ $value.syncwave | quote }}
  labels:
    openshift.io/cluster-monitoring: "true"
    {{- include "rhacs.labels" $ | nindent 4 }}
{{- if $value.operatorgroup.notownnamespace }}
spec: {}
{{- else }}
spec:
  targetNamespaces:
  - {{ $value.namespace }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}