apiVersion: v2
name: rhacs-demo-applications
description: Deploy a demo application with known SECURITY RISKS!!! Used for RHACS Demos
type: application
version: 1.0.3
appVersion: "1.16.0"
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/rhacs-demo-applications
icon: https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/redhat.svg
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
sources:
  - https://github.com/tjungbauer/helm-charts
keywords:
  - securitytesting
annotations:
  artifacthub.io/category: security
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: B677CB52F8358FA091044E375D24D6846DBA8F8A
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/B677CB52F8358FA091044E375D24D6846DBA8F8A
  artifacthub.io/changes: |
    - kind: fixed
      description: Signing Chart
