apiVersion: v2
name: rhacm-full-stack
description: Master chart to deploy RHACM operator
version: 1.0.10
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/rhacm-full-stack
icon: https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/redhat.svg
dependencies:
  - name: helper-operator
    version: "1.0.14"
    repository: https://charts.stderr.at/
  - name: helper-status-checker
    version: ~3.0.0
    repository: https://charts.stderr.at/
    condition: helper-status-checker.enabled
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
sources:
  - https://github.com/tjungbauer/helm-charts
keywords:
  - clustermanagement
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: B677CB52F8358FA091044E375D24D6846DBA8F8A
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/B677CB52F8358FA091044E375D24D6846DBA8F8A
  artifacthub.io/changes: |
    - kind: fixed
      description: Signing Chart
