---
override-rhacm-operator-version: &rhacmversion release-2.7

# Install Operator RHACM
# Deploys Operator --> Subscription and Operatorgroup
# Syncwave: 0
helper-operator:
  operators:
    advanced-cluster-management:
      enabled: true
      syncwave: '0'
      namespace:
        name: open-cluster-management
        create: true
      subscription:
        channel: *rhacmversion
        approval: Automatic
        operatorName: advanced-cluster-management
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: true
        notownnamespace: false

helper-status-checker:
  enabled: true

  operatorName: advanced-cluster-management

  # space separate list of deployments which shall be checked for status
  deployments: "multicluster-operators-application multicluster-observability-operator multicluster-operators-channel multicluster-operators-hub-subscription multicluster-operators-standalone-subscription multicluster-operators-subscription-report multiclusterhub-operator submariner-addon"

  wait_time: 60  # wait time in seconds for the check-job to verify when the deployments should be ready

  namespace:
    name: open-cluster-management

  serviceAccount:
    create: true
    name: "status-checker"

rhacm:
  namespace:
    name: open-cluster-management
  multiclusterhub:
    enabled: true
    syncwave: '3'
    # availabilityConfig: High # Might be High or Basic
