---
override-rhacm-operator-version: &rhacmversion release-2.6

# Install Operator RHACM
# Deploys Operator --> Subscription and Operatorgroup
# Syncwave: 0
helper-operator:
  operators:
    advanced-cluster-management:
      enabled: true
      syncwave: '0'
      namespace:
        name: open-cluster-management
        create: true
      subscription:
        channel: *rhacmversion
        approval: Automatic
        operatorName: advanced-cluster-management
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: true
        notownnamespace: false

rhacm:

  job_vars:
    max_attempts: 20  # How otften shall the status of the operator be checked (Default 20)
    wait_time: 20  # If the Deployments are not ready yet, how long shall I wait in addition (Default 20)
    crd_check_time: 5  # Time to sleep before I verify that the CRDs have been created

  namespace:
    name: open-cluster-management
    syncwave: '0'

serviceAccount:
  create: true
  name: "sa-acm"
