---
# General values
#
# Set cluster names ... Unfortunately the openshift-gitops operator keeps
# removing the secret of the *mgmtclustername (local cluster),
# therefor we switch to list generator
# https://issues.redhat.com/browse/GITOPS-1777
mgmt-cluster: &mgmtcluster https://kubernetes.default.svc
mgmt-cluster-name: &mgmtclustername in-cluster
production-cluster: &prodcluster https://cluster-api-url:6443
production-cluster-name: &prodclustername prod

repourl: &repourl 'https://github.com/tjungbauer/openshift-cluster-bootstrap'
repobranch: &branch main

argocd_projects:
#  - *mgmtclustername

applicationsets:
  generic_clusterconfig:
    enabled: true
    description: "Deploy generic cluster configuration, like banners or etcd encryption"
    labels:
      category: cluster-configuration
    path: clusters/all/clusterconfig/
    per_cluster_helm_values: true
    generatorclusters: []
#    repourl: "" # Optional
#    targetrevision: "" # Optional

  # Example using MULTIPLE SOURCES in an ApplicationSet
  # NOTE: As of Sep 2023 multiple sources is TechPreview. Currently, it is not supported in the UI or in the CLI

  # Name of the ApplicationSet. The clustername will be appended to the Application
  etcd-encryption:
    # Is the ApplicationSet enabled or not
    enabled: false

    # Description - always usful
    description: "Enable Cluster ETCD Encryption"

    # Any labels you would like to add to the Application. Good to filter it in the Argo CD UI.
    labels:
      category: security

    # Helm settings
    # These settings are used for single sources MAINLY.
    #
    # "per_cluster_helm_values" (bool, optional): Defines if every cluster known in Argo CD is using a spearate values-file. This values-file must be named <cluster-name>-values.yaml
    # "releasename" (string, optional): Overwrites the releasename of the chart
    # "paramters" (array, optional): Sets custom parameters for this chart. The list looks like:
    #      - name: Name/key of the parameter
    #      - value: value of the parameter
    helm:
      per_cluster_helm_values: false
    generatorlist:
      - clustername: *mgmtclustername
        clusterurl: *mgmtcluster
        chart_version: 1.0.16
      - clustername: *prodcluster
        clusterurl: *prodclustername
        chart_version: 1.0.13
    multiple_sources:
      - repoUrl: https://github.com/tjungbauer/openshift-cluster-bootstrap
        targetRevision: main
        ref: values
      - repoUrl: "https://charts.stderr.at/"
        chart: generic-cluster-config
        # Only set here, when it is not set in generatorlist
        # This is the version that will be used on all clusters
        # default_version: x.x.x
        helm:
          default_values_file: $values/clusters/all/etcd-encryption/values.yaml
          # additional_values_files:
          #  - example1.yaml
          #  - exampl2.yaml
          # helmvalues:
          #  - name: example
          #    value: values
          # releaseName: example


  # A collection of MANAGEMENT operators,
  # installed usually on the management cluster only.
  install-mgmt-operator-collection:
    enabled: false
    description: "Deploy a collection of Operators which are usually installed on a management cluster only"
    labels:
      category: operators
    path: charts/collection-management-operators
    generatorlist:
      - clustername: *mgmtclustername
        clusterurl: *mgmtcluster
    autosync_enabled: false  # should be disabled for operators
    repourl: "https://github.com/tjungbauer/helm-charts"
    targetrevision: "main"


applications:
  in-cluster-init-rhacs:
    enabled: false
    server: *mgmtcluster
    project: default
    description: "Initialize Red Hat Advanced Cluster Security and deploy Central and SecuredCluster"
    labels:
      category: security
      solution: rhacs
    source:
      path: charts/rhacs-full-stack
      repourl: "https://github.com/tjungbauer/helm-charts"
      targetrevision: "main"

# These define the default values.
# It is possible to overwrite repourl and targetrevision in the Applications(Sets)
general:
  argocd_project: 'default'
  source:
    repourl: *repourl
  branch: *branch
