{{- range .Values.ingresscontrollers }}
{{ if eq ( .enabled | toString) "true" }}
---
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: {{ .name }}
  namespace: openshift-ingress-operator
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
spec:
  replicas: {{ .replicas | default "2" }}
  {{- if .nodePlacement }}
  {{- with .nodePlacement }}
  nodePlacement:

{{- if .nodeSelector }}
{{- include "tpl.nodeSelector" . | indent 2 }}
{{- end }}

{{- if .tolerations }}
{{ include "tpl.tolerations" .tolerations | indent 4 }}
{{- end }}

  {{- end }}
  {{- end }}

{{- end }}
{{- end }}