{{ if .Values.monitoring }}
{{ if eq ( .Values.monitoring.enabled | toString) "true" }}
{{- with .Values.monitoring }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
  labels:
    {{- include "common.labels" $ | nindent 4 }}
data:
  config.yaml: |
    enableUserWorkload: {{ ( .enableUserWorkload | toString) | default "false" }}

    {{- /* ALERTMANAGER CONFIGURATION */}}
    {{- with .alertmanagerMain }}  
    alertmanagerMain:
      {{- if .disable_local_alertmanager }}
      {{- if or ( eq (.disable_local_alertmanager | toString) "true") (eq (.disable_local_alertmanager | toString) "false") }}
      enabled: {{.disable_local_alertmanager }}
      {{- end }}
      {{- end }}

      {{- if .secrets }}
      secrets:
        {{- range .secrets }}
        - {{.}}
        {{- end }}
      {{- end }}

      {{- if .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- end }}

      {{- if .tolerations }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
      {{- end }}

      {{- if .storage }}
      volumeClaimTemplate:
        spec:
          storageClassName: {{ .storage.class | default "gp2-csi" }}
          resources:
            requests:
              storage: {{ .storage.size | quote | default "40Gi" }}
      {{- end }}

      {{- if .resources }}
      resources:
        {{- if .resources.limits }}
        limits:
          {{- toYaml .resources.limits | nindent 10 }}
        {{- end }}
        {{- if .resources.requests }}
        requests:
          {{- toYaml .resources.requests | nindent 10 }}
        {{- end }}
      {{- end }}


    {{- end }}

    {{- /* PROMETHEUS CONFIGURATION */}}
    {{- with .prometheusK8s }}
    prometheusK8s:
      {{- if .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- end }}

      {{- if .tolerations }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
      {{- end }}
      retention: {{ .retention | default "15d" }}
      collectionProfile: {{ .collectionProfile | default "full" }}
      {{- if eq (.retentionSize | toString) "0"}}
      {{- else }}
      retentionSize: {{ .retentionSize }}
      {{- end }}

      {{- if .storage }}
      volumeClaimTemplate:
        spec:
          storageClassName: {{ .storage.class | default "gp2-csi" }}
          resources:
            requests:
              storage: {{ .storage.size | quote | default "100Gi" }}
      {{- end }}

      {{- if .resources }}
      resources:
        {{- if .resources.limits }}
        limits:
          {{- toYaml .resources.limits | nindent 10 }}
        {{- end }}
        {{- if .resources.requests }}
        requests:
          {{- toYaml .resources.requests | nindent 10 }}
        {{- end }}
      {{- end }}
    {{- end }}
    
    {{- /* K8SPROMETHEUS ADAPTER CONFIGURATION */}}
    {{- with .k8sPrometheusAdapter }}
    k8sPrometheusAdapter:
      {{- if .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- end }}

      {{- if .tolerations }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
      {{- end }}

      {{- if .resources }}
      resources:
        {{- if .resources.limits }}
        limits:
          {{- toYaml .resources.limits | nindent 10 }}
        {{- end }}
        {{- if .resources.requests }}
        requests:
          {{- toYaml .resources.requests | nindent 10 }}
        {{- end }}
      {{- end }}
    {{- end }}

    {{- /* KUBE STATE METRIC CONFIGURATION */}}
    {{- with .kubeStateMetrics }}
    kubeStateMetrics:
      {{- if .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- end }}

      {{- if .tolerations }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
      {{- end }}

      {{- if .resources }}
      resources:
        {{- if .resources.limits }}
        limits:
          {{- toYaml .resources.limits | nindent 10 }}
        {{- end }}
        {{- if .resources.requests }}
        requests:
          {{- toYaml .resources.requests | nindent 10 }}
        {{- end }}
      {{- end }}
    {{- end }}

    {{- /* TELEMETER CLIENT CONFIGURATION */}}
    {{- with .telemeterClient }}
    telemeterClient:
      {{- if .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- end }}

      {{- if .tolerations }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
      {{- end }}

      {{- if .resources }}
      resources:
        {{- if .resources.limits }}
        limits:
          {{- toYaml .resources.limits | nindent 10 }}
        {{- end }}
        {{- if .resources.requests }}
        requests:
          {{- toYaml .resources.requests | nindent 10 }}
        {{- end }}
      {{- end }}
    {{- end }}

    {{- /* OPENSHIFT STATE METRIC CONFIGURATION */}}
    {{- with .openshiftStateMetrics }}
    openshiftStateMetrics:
      {{- if .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- end }}

      {{- if .tolerations }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
      {{- end }}

      {{- if .resources }}
      resources:
        {{- if .resources.limits }}
        limits:
          {{- toYaml .resources.limits | nindent 10 }}
        {{- end }}
        {{- if .resources.requests }}
        requests:
          {{- toYaml .resources.requests | nindent 10 }}
        {{- end }}
      {{- end }}
    {{- end }}

    {{- /* MONITORING PLUGIN CONFIGURATION */}}
    {{- with .monitoringPlugin }}
    monitoringPlugin:
      {{- if .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- end }}

      {{- if .tolerations }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
      {{- end }}

      {{- if .resources }}
      resources:
        {{- if .resources.limits }}
        limits:
          {{- toYaml .resources.limits | nindent 10 }}
        {{- end }}
        {{- if .resources.requests }}
        requests:
          {{- toYaml .resources.requests | nindent 10 }}
        {{- end }}
      {{- end }}
    {{- end }}

    {{- /* THANOS QUERIER CONFIGURATION */}}
    {{- with .thanosQuerier }}
    thanosQuerier:
      {{- if .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- end }}

      {{- if .tolerations }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
      {{- end }}

      {{- if .resources }}
      resources:
        {{- if .resources.limits }}
        limits:
          {{- toYaml .resources.limits | nindent 10 }}
        {{- end }}
        {{- if .resources.requests }}
        requests:
          {{- toYaml .resources.requests | nindent 10 }}
        {{- end }}
      {{- end }}
    {{- end }}

    {{- with .prometheusOperator }}
    prometheusOperator:
      {{- if .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- end }}

      {{- if .tolerations }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
      {{- end }}

      {{- if .resources }}
      resources:
        {{- if .resources.limits }}
        limits:
          {{- toYaml .resources.limits | nindent 10 }}
        {{- end }}
        {{- if .resources.requests }}
        requests:
          {{- toYaml .resources.requests | nindent 10 }}
        {{- end }}
      {{- end }}
    {{- end }}

{{- end }}
{{- end }}
{{- end }}