{{- with .Values.gitops }}
{{ if eq ( .enabled | toString) "true" }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-gitops-operator
  namespace: {{ .namespace.name | default "openshift-gitops-operator" | quote }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
spec: {}
{{- end }}
{{- end }}
