---

quay:
  enabled: false
  config_bundle: config-bundle-secret
  syncwave: 3
  # public_route: route

  namespace:
    create: false
    name: quay-enterprise
    syncwave: 1

  job_init_quay:
    enabled: false
    syncwave: 5
    serviceAccount: quay-initiator

# Install Quay Operator
# Deploys Operator --> Subscription and Operatorgroup
# Syncwave: 0
helper-operator:
  operators:
    quay-operator:
      enabled: false
      syncwave: '0'
      namespace:
        name: openshift-operators
        create: false
      subscription:
        channel: stable-3.9
        approval: Manual
        operatorName: quay-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: false
        notownnamespace: true

# Using sub-chart helper-status-checker
helper-status-checker:
  enabled: false

  checks:

    - operatorName: quay-operator
      namespace:
        name: openshift-operators
      syncwave: 3

      serviceAccount:
        name: "sa-quay"
