apiVersion: v2
name: compliance-operator-full-stack
description: Master chart to deploy and configure the Compliance Operator
version: 1.0.17
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/compliance-operator-full-stack
icon: https://github.com/tjungbauer/helm-charts/raw/gh-pages/images/compliance-operator.png
dependencies:
  - name: helper-operator
    version: "1.0.15"
    repository: https://charts.stderr.at/
  - name: helper-status-checker
    version: ~3.0.0
    repository: https://charts.stderr.at/
    condition: helper-status-checker.enabled
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
sources:
  - https://github.com/tjungbauer/helm-charts
