apiVersion: v2
name: compliance-operator-full-stack
description: Master chart to deploy and configure the Compliance Operator
version: 1.0.8
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/compliance-operator-full-stack
icon: https://avatars.githubusercontent.com/u/40638982?s=200&v=4
dependencies:
  - name: helper-operator
    version: "1.0.7"
    repository: https://tjungbauer.github.io/helm-charts/
maintainers:
  - name: tjungbauer
