{{- with .Values.quay }}
{{ if eq ( .job_init_quay.enabled | toString) "true" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: init-user
  namespace: {{ .namespace.name }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: {{ .job_init_quay.syncwave | quote }}
spec:
  encryptedData:
    mail: AgAjfelMWSVbNAL1k0isrrh0s+EqHwEptX4GJtGcnmImTsffkwz93EBqQ9mP5GoGdjifspn/3veNhCiHQy/PE4fwv1TrHxiFU5GxJXVjzOaSbFAIFpoyJ1IZBId1S5PMWTPy3p9aikbBbRPzRtYBRy0hzIwZ/JoMOoCNu4dvsPoSEdnw+CyNxJMfotpJCiK9N2QI3EBVwPFe5S4Bg304jig3+rCm8nOlPOcNRd8r85WUlLZqCPicBzTMy4O95n/qiwNXH2BLDGnbnH7XjTMWon9xIdbRFQ3j0FOcG00QXK9YVMCb4/rWHX4UCgh1fmNoLn34QJJiEgWQoXG/nb5W6oYsF3HBTFALTFf13zi9xMMxJRKU20335O1e9XkiZoj7cS8sdq+ZvjEqVa3hHP2pz+yMWgL9R26DGswPT6k6VwjSb878Hn6SRiMmf3ejVd6I58SYXPkrmuffFk9ikavDR9mGY2Z0hu79MPowLtGP5KVYLhmKXIlkEduyUOGgiqyoYb6t9dIYM3Q3mYE4tjgK9ErwRCtMfBCg9ROPwZrGjL/GtxRCPiwpm1tSS93bnegLZGo37D5AKE+W8mp2+c3rzZdWKsY/SbFg75L4ewawpWz9g65eGwV5m/biY4hzuML+csqh6LOWkrgUGn1nHQYIVCeWv/AoxW9pUVonS5knpgMF1q8ANyUMPHmT8zoa/jEpvO0qvMsQ/vUsqSIcYTXB9KhZiWYZ
    password: AgDiEMUyym0gRyFc8AYWUuUL+VWMlamZTOdKAqBOpCZn027ocRYLQ4TiwlU8bXJ9Q6jaXcbniiSG1eJZhoDv/O1OdknOhg3LCRxKnKMsdY1KPFJFVc44imLzEUD+NnNEDKr+2PKdyIUdqwMAftDtXSfHJ+BaX9YzlMq0I6MzKyEMjm0UjUne2fdkYi9MKFY01rNcH/BNvachwgpIslinfOWbJgIxK0L5ygoEhABE9n+Hq3qPH0Q7KqxD/Co/cvLRLMrYa6ZNqyKGozVKUYlBH/VeCdHMESaPNiWGBxkHi1TWfVK14syFAEeSvhbcbU28QFe4KXQTp1dfLa+g5AIUiqt3m/NyiOpioJ7T9FJFu7olDLASt0f9IjjHFL0zhXwfVDaVTpu77x/QkErnqBz9coEaNmE6BuUvj+cIxanKPrnV/+nftnW8rlkk2cTemYDkdHCiRtGwKHbmgx4Uhsf/65batECKvY0RmZwpEHbn4zJBgdl0ycA2N+7tzab+Dv1M+Cn/b4E/y/cbIUFu08Y1djIBF9yVzMcaqNNMMb5xoQ/AS77hf5J/2mNdCNoVUmAzsL6fNvRxNPJfUCpsSun/E5HFgqTAWDxJR9ZPC+QdSCjGBrrhtlwOVZXrGM9Q4sfsz7zBwtWBHrSAuyqc/AP8bvlpS+69FSI9SkjVdeBavgic4PCTomI7Vhzk5HDF/r4dKAxY/tDNFsfDdkRMFFtjKOwrmw4pRR4BsQ==
    username: AgClv08WHRof1K1I2g9mh3Wo9ZqvY6lH+HQkiLp6mwBrho1qTZ1Ufi3kOSgx7kDgFB0tLzuHRvVefybDL6CNhUIcgoTw4qw1K78oveaHakTKoH9qG7SLNHGUWKIup/vjOxE/0X4ASG1rKXhrySUWK3fb1zqwdyT5OMPNzMfTR8oTlxdoL0/xcuQLHBbCHW/3zWrDwhmLfEcer+BSyNIW6cUVzxjG9c9jQHzGuPnhNvp2LkgRa1XsxmUcvkbFcr0n7EGzHcGs+lABDdkjXH2N316h1uPclgvGhQkVuy5jLtJLOqsDIhMfl54ll+pA+8tBQZ/pPLcfSlvc8wIGjF13GLLjoyI/bVeOFKfRCxNJKEzArr17iKh+MejR0x5IlQIvanHmxnvmjSeLqPB3BNYPaInLQQ4bijmvDOBd1jSgt/A9ACL0YRIOLe6ofqN05yCeyCUZGg8d9NJ0zuTMFHqy2P2+RvZ4WB7sFKSrBQty6wUaOyEkB1+gbqlHEaEF5q4cqY/lufvZ3s4/g9OsEB2XfNpaTBZlC+OSqHEeQwssxqUVxIIU0+BP1my3dittvp/pMDW+Oxk2mCXVnPU+hK7cZ9oJJ4MQZaYM771zYXUUrz6Lj2aNeG4cN9kN5QH7uiC7StOmYOpv6e9g+/+xdh5Q/wvD5aAj4A7wIpUJ8vfqCmECyDVqGuJJvumQeiKEzpevQBnl3KWCe5Waowg=
  template:
    metadata:
      creationTimestamp: null
      name: init-user
      namespace: {{ .namespace.name }}
{{- end }}
{{- end }}