{{- with .Values.quay }}
{{ if eq ( .job_init_quay.enabled | toString) "true" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .job_init_quay.serviceAccount }}
  namespace: {{ .namespace.name | quote }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: {{ .job_init_quay.syncwave | quote }}
{{- end }}
{{- end }}