{{- if eq ( .Values.quay.enabled | toString) "true" }}
{{- if eq ( .Values.quay.init_user.enabled | toString) "true" }}
{{- with .Values.quay }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .init_user.secretName | default "init-user" }}
  namespace: {{ .namespace.name }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: {{ .job_init_quay.syncwave | quote }}
data:
  mail: {{ .init_user.mail | default "admin@company.com" | b64enc }}
  username: {{ .init_user.username | default "admin" | b64enc }}
  {{- if .init_user.password }}
  password: {{ .init_user.password | b64enc }}
  {{- else }}
  password: {{ randAlphaNum 16 | b64enc }}
  {{- end }}
type: Opaque
{{- end }}
{{- end }}
{{- end }}