{{- range $key, $value := .Values.applications }}
{{ if eq ($value.enabled | toString) "true" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '5'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    gitops.ownedBy: cluster-config
    {{- include "argo.labels" $ | nindent 4 }}
    {{- if $value.labels }}
    {{- range $key_labels, $value_labels := $value.labels }}
    {{ $key_labels }}: {{ $value_labels }}
    {{- end }}
    {{- end }}
  name: {{ $key | replace "_" "-" }}
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: {{ .server }}
  project: {{ .project }}
  source:
    path: {{ .source.path }}
    repoURL: {{ .source.repourl | default $.Values.general.source.repourl }}
    targetRevision: {{ .source.targetrevision | default $.Values.general.branch }}
  info:
    - name: Description
      value: {{ .description | default "No Description" }}
{{- end }}
{{- end }}