apiVersion: v2
name: generic-cluster-config
description: This Chart is responsible to deploy generic clusterconfiguration, for example etcd encryption, oauth etc.
version: 1.0.12
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/generic-cluster-config
icon: https://github.com/tjungbauer/helm-charts/raw/gh-pages/images/configuration.png
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
sources:
  - https://github.com/tjungbauer/helm-charts
