# Example

etcd_encryption:
  enabled: false

self_provisioner:
  deactivate: false

idp:
  enabled: false
  providers:
    htpasswd:
      - name: HTPASSWD
        enabled: false
        secretname: htpasswd-secret
    ldap:
      - name: LDAP
        enabled: false
        url: 127.0.0.1
        insecure: true
        binddn: xyz
        preferredusername: sAMAccountName