{{- range $key, $value := .Values.namespaces }}
{{ if eq ( .enabled | toString) "true" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name | replace "_" "-" | quote }}
  labels:
    openshift.io/cluster-monitoring: "true"
    {{- include "common.labels" $ | nindent 4 }}
{{- end }}
{{- end }}
