{{ if eq ( .Values.namespace.create | toString) "true" }}
{{ if eq ( .Values.set_admin_password | toString) "true" }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admin-sonarqube
  labels:
    {{- include "common.labels" $ | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Values.namespace.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
{{- end }}
{{- end }}

