{{ if eq ( .Values.set_admin_password | toString) "true" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: sonarqube
spec:
  encryptedData:
    adminpass: AgDaJQtiOrzoGz+EGsjEcy5kajDzTfN8vgocZdPqnxc+xtcl6Vfe7bCYoqzxX7KbdVOD/JDYamlq6CzR9M8dc2qPF2BkOYIjPcXzmicu9jclIT0S0PIkikR+jy2QRBHji2w6unrgmyVmMtJ+gKavl4I9UwRrqK5l6NgHwjHknCv3be81atPe7jW3tjQwooCfXe99MldG0Koa5bPFlwYbX7L1OXVxWRc3I82av7z6DuJA0iIGZPJdX+SE4esjk6g8fV43M66CgzAl8OGpp1zRi+VR2Bejn1HUIfUA8757qMG7+sJT1CVSqKdsbWKvsJfTr30gUYCX2WuZymyfEYVecRuBjgjhOvBv+t/Fp/MIxvCtxfdQIIO0KFb1JX+YhWcxPGsNoQYjxtBAefZifxsA5tclvT0S3wcD2xzAEpcMM2mGJyC+GfDNHt13lKyyUf41g+UF49C7AjoT3Ze3tcWGU4AYdbTutWOmVATqjlRMgdYCmRD8LAH0Rz3BlYMCCzUb253fLuFgz47TNqVzBKGaL07hEtHD1rCTjmtPdlU0TFl3kW/xFR++ZqzyuHt3lFXjuaXsUOHuRPzKjOV92vYqz00WKFSgWbXbKGhO3xQft1orI9k/YkX6apClxl84ZR9XhYk3YSf6/bhNlCiMzdPE0cW/SIYzbx0V8xr3Zij9TTRFOqMNfLkSDUfHciXuJZ6YmW+crgesR1/eEw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: credentials
      namespace: sonarqube
{{- end }}
