---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: sonarqube
spec:
  encryptedData:
    adminpass: AgBMUvxxDMdczHSVAR77CeRJMCBS4GjvxIz1T8iqxUsBnTTh9OGm9PoSjVd1uM9OZ82wH5PMU6geh+6WdBvnmWMsj51sVvXaJL+tYUz8wlmxPQ+kTAyNBdlriXARgTNj8MdIIRs7t37F5rDANXMwvtIttrL5YjEJSxOZR6oSaSJdOJ8ozo05QojY/fWzWaxRc2CnhQTGuuCnNijzvihYPqOuxbmgxAUu0Y97a5LP+jU1xwShGX5ohNkEseVlxhyUSDLlBKasmFm25lvMaVey2fg4vnOsdh1nGzEx4pREufGNLyEUe2zy45CcFFU3aAB62T9HwiHGBNoz6WOtZ2nJ3a6caM5MU6FJ/K9kxfSPg3lrxSUbkwQ5jKRS3SemP+E/TQPzk0gzWnHdf8J8520AJbz8toARQSH3rOINse6MYcgx6z2QsGPOQgLzkI3+AX6ytnyedqodrddgR2UK2OhDC9eGJJHENCtX9cpZh7AnExw0YAP7ocpW0MqnTgJ18ow4knq4uoAVjDb9vEFv5k4XH6Ldm4ikdZ+vep2MvZ//GTbbiPglO2iByA5dZkUiR5iFgLwK+WHEZjygczCXzY/BIBOUiD2cuHv0vByIQoIF1xSj1FUnns3U66Lx/L6PpurJUa/EELdxhiKc82y4+4+ZI5bG9iiAfq7zFzlWbaUpcEN09wZb5Uj1S7j5jQ+KPhs/Eo7iIajXc3keDg==
  template:
    metadata:
      creationTimestamp: null
      name: credentials
      namespace: sonarqube
