---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: sonarqube
spec:
  encryptedData:
    adminpass: AgCdN6+DXnjNXg0jqglk/d6FblCgv+IhP3Yrci2NqI0rlMrCTL9vpVlo5Fp/d+tDJiFZKkvvv2ZY/WPeYDVad7ydzdfGDJdwJnsHLADp0QC15IcvPJB60RyQa3TuMjgC4t8QSDNd0FexhlCd7CMKUUEGYqHjh+futew4JqpfLNPjtSLTjj8GyVwfq6B7BwC6nmPif1TPKtDTaoIezyyYgFovmz6m45KxCn11IwDXZsGCBLjSDrxRueNRatyBh7bHlUFmRnrr7f8hn2oQ1fbD0DfK/NGZeGNiTNOfJksNswqw4dTJbKooEAzpWtG5lTcciR7tO9mZsaCDE/k1zMQmlXsnNQIxfHsp3VVQ7CZ6y6ab2Cl/wf3HI3ZQt71/HOfjwoT43C0c4yXV+Pn9Ud25CTqGRCfqZMdC4cw8p9ZbcdO5bs7jHykhAKswPSdaKxGhadqgpVnL6SJGqMs+1xjnYiyHfQ4qwRWLWfOsj/65gRSCJp+h3MpajPYdTS0wOyb7JsS8PpRjUMJ9B9lY+XoJlXEIIo7QWuwsdByDX9YvmkBUvYAGyv0dxpG6wm9srPQRRrmAnajaGp/7RAhmjy56dHKbgJ4bKObUL1NArc1Zzs6h1lQUFU2hlHAre8KihH0Dgxk7NqQC2xNrwOlIqXFO9G6/cV5wKerPodkAUTzQIzR9OEdUiZF3TXkUc1wwexM0UYk/LbjEQ4Ad3A==
  template:
    metadata:
      creationTimestamp: null
      name: credentials
      namespace: sonarqube
