{{ if eq (.Values.rhacs.secured_cluster.enabled | toString) "true" }}
---
apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.rhacs.secured_cluster.syncwave | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: {{ .Values.rhacs.secured_cluster.clustername | default "local-cluster" | replace "_" "-" | replace "." "-" }}
  namespace: {{ .Values.rhacs.namespace.name | quote }}
  labels:
    openshift.io/cluster-monitoring: "true"
    {{- include "rhacs.labels" $ | nindent 4 }}
spec:
  clusterName: {{ .Values.rhacs.secured_cluster.clustername | default "local-cluster" }}
  {{ if .Values.rhacs.secured_cluster.centralEndpoint }}
  centralEndpoint: {{ .Values.rhacs.secured_cluster.centralEndpoint }}
  {{- end }}
  admissionControl:
    listenOnCreates: false
    listenOnEvents: true
    listenOnUpdates: false
    {{- if .Values.rhacs.secured_cluster.admissioncontrol.tolerations }}
    {{- range $key, $value := .Values.rhacs.secured_cluster.admissioncontrol.tolerations }}
    tolerations:
      - effect: {{ $value.effect }}
        key: {{ $value.key }}
        operator: {{ $value.operator }}
        value: {{ $value.value }}
    {{- end }}
    {{- end }}
  {{- if .Values.rhacs.secured_cluster.sensor.tolerations }}
  {{- range $key, $value := .Values.rhacs.secured_cluster.sensor.tolerations }}
  sensor:
    tolerations:
      - effect: {{ $value.effect }}
        key: {{ $value.key }}
        operator: {{ $value.operator }}
        value: {{ $value.value }}
  {{- end }}
  {{- end }}
  perNode:
    collector:
      collection: EBPF
      imageFlavor: Regular
    taintToleration: TolerateTaints
{{- end }}
