apiVersion: v2
name: helper-objectstore
description: A helper Chart to create BackingStore, BackingClass, BucketClaim and StorageClass objects, when ODF is used. Currently on type PV is supported!
version: 1.0.0
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/helper-operator
icon: https://github.com/tjungbauer/helm-charts/raw/gh-pages/images/helping.png
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
sources:
  - https://github.com/tjungbauer/helm-charts
keywords:
  - helper
  - subchart
  - odf
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: B677CB52F8358FA091044E375D24D6846DBA8F8A
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/B677CB52F8358FA091044E375D24D6846DBA8F8A
  artifacthub.io/changes: |
    - kind: added
      description: initial release
