apiVersion: v2
name: collection-management-operators
description: Collection of management Operators which are usually installed on the management cluster only. I.e. Quay, ACM, Cert-Manager...
version: 1.0.11
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/collection-management-operators
icon: https://keithtenzer.com/assets/2020/01/38202270.png
dependencies:
  - name: helper-operator
    version: "1.0.9"
    repository: https://charts.stderr.at/
maintainers:
  - name: tjungbauer
