{{- with index .Values "helper-operator" }}
{{- range $key, $value := .operators }}
{{ if eq ($value.enabled | toString) "true" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: {{ include "compliance.rolename" $ }}-role
  namespace: {{ $.Values.compliance.namespace.name | quote }}
  labels:
    {{- include "compliance.labels" $ | nindent 4 }}
rules:
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - get
      - list
{{- end }}
{{- end }}
{{- end }}