{{- range $key, $value := .Values.operators }}
{{ if eq ($value.enabled | toString) "true" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "compliance.serviceAccountName" $ }}
  namespace: {{ $.Values.compliance.namespace.name | quote }}
  labels:
    {{- include "compliance.labels" $ | nindent 4 }}
{{- end }}
{{- end }}