{{ if .Values.monitoring }}
{{ if eq ( .Values.monitoring.enabled | toString) "true" }}
{{- with .Values.monitoring }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
  labels:
    {{- include "common.labels" $ | nindent 4 }}
data:
  config.yaml: |
    enableUserWorkload: {{ ( .enableUserWorkload | toString) | default "false" }}
    alertmanagerMain:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
      volumeClaimTemplate:
        metadata:
          name: ocs-alertmanager-claim
        spec:
          storageClassName: {{ .alertmanagerMain.storageclass }}
          resources:
            requests:
              storage: {{ .alertmanagerMain.storage }}
    prometheusK8s:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
      retention: {{ .prometheusK8s.retention }}
      volumeClaimTemplate:
        metadata:
          name: ocs-prometheus-claim
        spec:
          storageClassName: {{ .prometheusK8s.storageclass }}
          resources:
            requests:
              storage: {{ .prometheusK8s.storage}}
    prometheusOperator:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
    k8sPrometheusAdapter:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
    kubeStateMetrics:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
    telemeterClient:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
    openshiftStateMetrics:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
    monitoringPlugin:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
    thanosQuerier:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
{{- end }}
{{- end }}
{{- end }}