{{- with .Values.workload_monitoring }}
{{ if eq ( .enabled | toString) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
  labels:
    {{- include "common.labels" $ | nindent 4 }}
data:
  config.yaml: |
    enableUserWorkload: true
{{- end }}
{{- end }}