ep: &endpoint sonarqube.apps.ocp.aws.ispworld.at

namespace:
  name: sonarqube
  create: true

set_admin_password: true

endpoint: *endpoint

# Sonarqube Settings
sonarqube:
  OpenShift:
    enabled: true
    createSCC: true
  persistence:
    enabled: true
  networkPolicy:
    enabled: false
  ingress:
    enabled: true
    hosts:
      - name: *endpoint
        path: /
  plugins:
    install:
      - https://github.com/checkstyle/sonar-checkstyle/releases/download/10.9.3/checkstyle-sonar-plugin-10.9.3.jar
      - https://github.com/dependency-check/dependency-check-sonar-plugin/releases/download/3.1.0/sonar-dependency-check-plugin-3.1.0.jar
      - https://github.com/sbaudoin/sonar-yaml/releases/download/v1.7.0/sonar-yaml-plugin-1.7.0.jar
      - https://github.com/sbaudoin/sonar-shellcheck/releases/download/v2.5.0/sonar-shellcheck-plugin-2.5.0.jar
     # - https://github.com/SonarQubeCommunity/sonar-l10n-de/releases/download/1.2/sonar-l10n-de-plugin-1.2.jar
