apiVersion: v2
name: helm-policy-generator
description: This Chart shall help to generate policies for Advanced Cluster Management
version: 1.0.1
icon: https://github.com/tjungbauer/helm-charts/raw/gh-pages/images/helping.png
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/helm-policy-generator
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
sources:
  - https://github.com/tjungbauer/helm-charts
keywords:
  - helper
  - acm
  - policy
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: B677CB52F8358FA091044E375D24D6846DBA8F8A
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/B677CB52F8358FA091044E375D24D6846DBA8F8A
  artifacthub.io/changes: |
    - kind: added
      description: Initial Release
    - kind: added
      description: descriptions in example values-files and some minor changes for optional parameters
