policyGenerator:
  policyDefaults:
    # The disabled parameter provides the ability to enable and
    # disable your policies
    #
    # Set the value to true or false
    # Default: true (explicitly set the value to false to activate the policy)
    disabled: false

    # The name for identifying the policy resource.
    policyname: console-banner

    # Namespace of the policy, must exist!
    namespace: policies-hub

    # Description of the policy.
    #
    # Optional
    # Default: empty
    description: ''

    # A security control category represent specific requirements
    # for one or more standards. For example, a System and Information Integrity category
    # might indicate that your policy contains a data transfer protocol
    # to protect personal information, as required by the HIPAA and PCI standards.
    #
    # Optional
    # Default: empty
    categories:
      - CM Configuration Management

    # The name of the security control that is being checked. For
    # example, Access Control or System and Information Integrity.
    #
    # Optional
    # Default: empty
    controls:
      - CM Console Customizations

    # The name or names of security standards the policy is related to.
    # For example, National Institute of Standards and Technology (NIST)
    # and Payment Card Industry (PCI).
    #
    # Optional
    # Default: empty
    standards:
      - Baseline 2023v1

    # Specifies the remediation of your policy. The parameter values are
    # enforce and inform. If specified, the spec.remediationAction
    # value that is defined overrides any remediationAction
    # parameter defined in the child policies in the policy-templates
    # section. For example, if the spec.remediationAction value
    # is set to enforce, then the remediationAction in the
    # policy-templates section is set to enforce during runtime.
    
    # Important: Some policy kinds might not support the enforce feature.
    #
    # Optional
    # Values:
    #   - inform
    #   - enforce
    remediationAction: inform

# Places a policy to a cluster with selected labels and or clusterSet
placement:
  # a clusterSet the policy to bind to. The clusterSet must exist.
  # Optional
  # clusterSets:
  #   - hub

  # required cluster selectors
  # Selects a cluster based on its labels. For example: name euqals to "local-cluster"

  # multiple selectors can be defined, which must all be true
  lableSelectors:
    - key: name
      operator: In
      values:
        - local-cluster

# The policy set controller aggregates the policy status scoped to policies that are defined in the same namespace.
policySet:
  # Enable of disable policySets.
  # If disabled, the PlaceMentBinding will use the name of the policy
  enabled: false
  sets:
      # The name for identifying the policySet resource.
    - name: console-customizations
      description: "Contains console customizations"

      # The list of policies that you want to group together in the policy set.
      policies:
        - console-banner
