apiVersion: v2
name: openshift-data-foundation
description: Deploys the OpenShift Data Foundation Operator
version: 1.0.0
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/openshift-data-foundation
icon: https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/redhat.svg
dependencies:
  - name: helper-operator
    version: "1.0.9"
    repository: https://tjungbauer.github.io/helm-charts/
maintainers:
  - name: tjungbauer
