{{- with .Values.storagecluster }}
{{ if eq ( .enabled | toString) "true" }}
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncwave | default "3" | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    {{- include "common.labels" $ | nindent 4 }}
{{- if eq ( .multigateway_only.enabled | toString) "true" }}  
spec:
  multiCloudGateway:
    dbStorageClassName: {{ .multigateway_only.storageclass }}
    reconcileStrategy: standalone

{{- end }}
{{- end }}
{{- end }}
