{{- with .Values }}
{{ if eq ( .enabled | toString) "true" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: {{ .syncwave | default 1 | quote }}
  name: {{ include "helper.rolename" $ }}-role
  namespace: {{ .namespace.name | quote }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
rules:
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - get
      - list
{{- end }}
{{- end }}