{{- with .Values }}
{{ if eq ( .enabled | toString) "true" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helper.serviceAccountName" $ }}
  namespace: {{ .namespace.name | quote }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
{{- end }}
{{- end }}
