{{- range $key, $value := .Values.operators }}
{{ if eq ($value.enabled | toString) "true" }}
{{- if $value.operatorgroup.create }}
---
apiVersion: v1
kind: Namespace
metadata:
 name: rhacs-operator
 labels:
   openshift.io/cluster-monitoring: "true"
{{- end }}
{{- end }}
{{- end }}
