helper-operator:
  namespaces:
    - name: codeready-workspaces
    - name: resource-locker-operator

  operators:
    codeready-workspaces:
      enabled: true
      namespace:
        name: codeready-workspaces
        create: true
      subscription:
        channel: latest
        approval: Automatic
        operatorName: codeready-workspaces
        sourceName: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: true

    resource-locker:
      enabled: true
      namespace:
        name: resource-locker-operator
        create: true
      subscription:
        channel: alpha
        approval: Automatic
        operatorName: resource-locker-operator
        sourceName: community-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: true
        notownnamespace: true

    netobserv:
      enabled: true
      namespace:
        name: openshift-operators
      subscription:
        channel: alpha
        approval: Automatic
        operatorName: netobserv-operator
        sourceName: community-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: false
