{{- if eq (.Values.enabled | toString) "true" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.clusterrolebindingPrivileged_name | default "etcd-backup-scc-privileged" }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount | default "etcd-backup" }}
  namespace: {{ .Values.namespace.name | default "etcd-backup" }}
{{- end }}
