apiVersion: batch/v1
kind: Job
metadata:
  name: check-operator-status
  namespace: {{ .Values.compliance.namespace.name | quote }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: '1'
  labels:
    {{- include "compliance.labels" $ | nindent 4 }}
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/ansible-automation-platform-21/ee-supported-rhel8:1.0
          command:
            - /bin/bash
            - -c
            - |
             #!/usr/bin/env bash
             # Wait for central to be ready
             sleep_timer={{ .Values.compliance.wait_time }}
             status=0

             echo "Waiting for operator to be available..."

             # turned out it takes even more time until operator is ready, so lets check the deployment
             deployments=(compliance-operator ocp4-openshift-compliance-pp rhcos4-openshift-compliance-pp)
             for i in "${deployments[@]}";
             do
                printf "\nWaiting for deployment %s\n" "$i";
                oc get deployment/"$i" -n {{ .Values.compliance.namespace.name | quote }}
                depl_status=$?
                if [ $depl_status -eq 1 ]; then
                    echo "Deployment not yet found... Give Operator $sleep_timer seconds to create the Deployment"
                    sleep $sleep_timer
                fi
                oc rollout status deployment "$i" -n {{ .Values.compliance.namespace.name | quote }}
                status=$?
             done

             echo $status

             if [ $status -eq 0 ]; then
                  echo "Operator seems to be ready"
             else
                  echo "ERROR: Operator is not ready"
                  exit 1
             fi
          name: check-operator
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      serviceAccount: {{ include "compliance.serviceAccountName" $ }}
      serviceAccountName: {{ include "compliance.serviceAccountName" $ }}