apiVersion: v2
name: collection-operators
description: Collection of Operators which can be deployed on Demo Systems.
version: 1.0.1
home: https://github.com/tjungbauer/helm-charts
icon: https://sdk.operatorframework.io/build/images/logo.svg
maintainers:
  - name: tjungbauer
