apiVersion: v2
name: collection-operators
description: Collection of Operators which can be deployed on Demo Systems.
version: 1.0.11
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/collection-operators
icon: https://keithtenzer.com/assets/2020/01/38202270.png
dependencies:
  - name: helper-operator
    version: "1.0.7"
    repository: https://tjungbauer.github.io/helm-charts/
maintainers:
  - name: tjungbauer
