---
helper-operator:
  override-rhacs-operator-version: &rhacsversion rhacs-3.69

  logging:
    # Might be needed with clusters that have an infra plane
    # nodeSelector:
    #   key: node-role.kubernetes.io/infra
    #   value: ''
  namespace: openshift-logging

  operators:
    openshift-pipelines-operator-rh:
      enabled: true
      namespace:
        name: openshift-operators
      subscription:
        approval: Automatic
        operatorName: openshift-pipelines-operator-rh
        sourceName: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: false

    elasticsearch-operator:
      enabled: true
      namespace:
        name: openshift-operators-redhat
        create: true
      subscription:
        approval: Automatic
        operatorName: elasticsearch-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: true

    cluster-logging-operator:
      enabled: false
      namespace:
        name: openshift-logging
        create: true
      subscription:
        approval: Automatic
        operatorName: cluster-logging
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: true

    servicemesh-operator:
      enabled: true
      namespace:
        name: openshift-operators
      subscription:
        approval: Automatic
        operatorName: servicemeshoperator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: false

    jaeger-operator:
      enabled: true
      namespace:
        name: openshift-operators
      subscription:
        approval: Automatic
        operatorName: jaeger-product
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: false

    kiali-operator:
      enabled: true
      namespace:
        name: openshift-operators
      subscription:
        approval: Automatic
        operatorName: kiali-ossm
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: false

    rhacs-operator:
      enabled: false  # is deployed using "rhacs-full-stack" folder
      namespace:
        name: rhacs-operator
        create: true
      subscription:
        channel: *rhacsversion
        approval: Manual
        operatorName: rhacs-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: true
        # rhacs does not support to monitor own namespace,
        # therefor the spec in the OperatorGroup must be empty
        notownnamespace: true
