{{- if .Values.costmgmt }}
{{- if eq ( .Values.costmgmt.enabled | toString) "true" }}
{{- with .Values.costmgmt }}
---
kind: CostManagementMetricsConfig
apiVersion: costmanagement-metrics-cfg.openshift.io/v1beta1
metadata:
  name: {{ .name }}
  namespace: costmanagement-metrics-operator
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncwave | default "10" | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    {{- include "compliance.labels" $ | nindent 4 }}
spec:
  {{- if eq ( .airgapped | toString) "true" }}
  authentication: {}
  {{- end }}
  packaging:
    max_reports_to_store: {{ .max_reports_to_store | default 30 }}
    max_size_MB: {{ .max_size_MB | default 100 }}
  prometheus_config:
    collect_previous_data: true
    context_timeout: 120
    disable_metrics_collection_cost_management: false
    disable_metrics_collection_resource_optimization: false
  {{- if eq ( .airgapped | toString) "true" }}
  source: {}
  {{- end }}
  upload:
    upload_cycle: {{ .upload_cycle | default 360 }}
    {{- if eq ( .airgapped | toString) "true" }}
    upload_toggle: false
    {{- else }}
    upload_toggle: true
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
