name: Lint and Test Charts

on: 
  push:
    branches: 
      - main
#    paths:
#      - 'charts/**'
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'README.md'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v2.1
        with:
          version: v3.8.1

      - uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then                                                                                                                                            echo "::set-output name=changed::true"
          else
            echo "::set-output name=changed::false"
          fi
    
      - name: Run chart-testing (lint)
        run: |
          echo ${{ steps.list-changed.outputs.changed }}
          if [ "${{ steps.list-changed.outputs.changed }}" ]; then
            echo "checking changed charts only"
            ct lint --target-branch ${{ github.event.repository.default_branch }}
          else
            echo "checking ALL charts"
            ct lint --all --target-branch ${{ github.event.repository.default_branch }}
          fi
