apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener
  namespace: {{ .Values.demo_pipelines }}
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: ClusterTriggerBinding
          ref: github-push
      interceptors:
        - params:
            - name: secretRef
              value:
                secretKey: secretToken
                secretName: github-secret
            - name: eventTypes
              value:
                - push
          ref:
            kind: ClusterInterceptor
            name: github
      template:
        ref: trigger-template-linting-gitops
