kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-pipeline-demo
  namespace: {{ .Values.demo_pipelines }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: gp2
  volumeMode: Filesystem
